apiVersion: v1
kind: Service
metadata:
  name: gateway
  namespace: default
  labels:
    app: gateway
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 8080
      nodePort: 30080
  type: NodePort
  selector:
    app: gateway
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
  namespace: default
  labels:
    app: gateway
    version: v1
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: gateway
      version: v1
  template:
    metadata:
      labels:
        app: gateway
        version: v1
    spec:
      serviceAccountName: shop
      containers:
        - image: registry.cn-shenzhen.aliyuncs.com/mrheaaaavy/shop-gateway:latest
          imagePullPolicy: Always
          name: gateway
          resources:
            requests:
              memory: "2Gi"
            limits:
              memory: "2Gi"
          command:
            - java
            - -Duser.timezone=Asia/Shanghai
            - -XX:ErrorFile=/dumps/hs_err_pid%p.log
            - -XX:+HeapDumpOnOutOfMemoryError
            - -XX:HeapDumpPath=/dumps/
            - -XX:+AlwaysPreTouch
            - -XX:+UseContainerSupport
            - -XX:+ParallelRefProcEnabled
            - -Xlog:gc*
            - org.springframework.boot.loader.JarLauncher
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 5
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 5
          ports:
            - containerPort: 8080
              name: http
          volumeMounts:
            - mountPath: /dumps
              name: heap-dumps
      volumes:
        - name: heap-dumps
          hostPath:
            path: /var/log/dumps/
