apiVersion: v1
kind: Service
metadata:
  name: gateway
  namespace: default
  labels:
    app: gateway
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 8080
  selector:
    app: gateway
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: gateway
  namespace: default
  labels:
    app: gateway
    version: v1
spec:
  replicas: 1
  serviceName: gateway
  selector:
    matchLabels:
      app: gateway
      version: v1
  template:
    metadata:
      labels:
        app: gateway
        version: v1
    spec:
      serviceAccountName: shop
      containers:
        - image: registry.cn-shenzhen.aliyuncs.com/mrheaaaavy/shop-gateway:latest
          imagePullPolicy: Always
          name: gateway
          resources:
            requests:
              memory: "2Gi"
            limits:
              memory: "2Gi"
          ports:
            - containerPort: 8080
              name: http
