apiVersion: v1
kind: Service
metadata:
  name: member-service
  namespace: default
  labels:
    app: member-service
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 8080
  selector:
    app: member-service
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: member-service
  namespace: default
  labels:
    app: member-service
    version: v1
spec:
  replicas: 1
  serviceName: member-service
  selector:
    matchLabels:
      app: member-service
      version: v1
  template:
    metadata:
      labels:
        app: member-service
        version: v1
    spec:
      serviceAccountName: shop
      containers:
        - image: registry.cn-shenzhen.aliyuncs.com/mrheaaaavy/shop-member-service:latest
          imagePullPolicy: Always
          name: member-service
          resources:
            requests:
              memory: "2Gi"
            limits:
              memory: "2Gi"
          ports:
            - containerPort: 8080
              name: http
