# Default values for shop-demo.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

image:
  pullPolicy: IfNotPresent

imagePullSecrets: []

serviceAccount:
  create: true
  name: "shop-demo"

memberService:
  image: "registry.cn-shenzhen.aliyuncs.com/mrheaaaavy/shop-member-service"
  tag: "latest"
  replicas: 1
  ports:
    external: 8081
    internal: 8081
  healthCheck:
    liveness:
      path: /actuator/health
      initialDelaySeconds: 10
      periodSeconds: 10
      successThreshold: 1
      failureThreshold: 3
    readiness:
      path: /actuator/health
      initialDelaySeconds: 10
      periodSeconds: 10
      successThreshold: 1
      failureThreshold: 3
  env:
    javaOpts: "-Duser.timezone=Asia/Shanghai -XX:+UseContainerSupport -XX:MaxRAMPercentage=80"
  resources:
    requests:
      memory: "2Gi"
    limits:
      memory: "2Gi"
  service:
    type: ClusterIP

productService:
  image: "registry.cn-shenzhen.aliyuncs.com/mrheaaaavy/shop-product-service"
  tag: "latest"
  replicas: 1
  ports:
    external: 8082
    internal: 8082
  healthCheck:
    liveness:
      path: /actuator/health
      initialDelaySeconds: 10
      periodSeconds: 10
      successThreshold: 1
      failureThreshold: 3
    readiness:
      path: /actuator/health
      initialDelaySeconds: 10
      periodSeconds: 10
      successThreshold: 1
      failureThreshold: 3
  env:
    javaOpts: "-Duser.timezone=Asia/Shanghai -XX:+UseContainerSupport -XX:MaxRAMPercentage=80"
  resources:
    requests:
      memory: "2Gi"
    limits:
      memory: "2Gi"
  service:
    type: ClusterIP

tradeService:
  image: "registry.cn-shenzhen.aliyuncs.com/mrheaaaavy/shop-trade-service"
  tag: "latest"
  replicas: 1
  ports:
    external: 8083
    internal: 8083
  healthCheck:
    liveness:
      path: /actuator/health
      initialDelaySeconds: 10
      periodSeconds: 10
      successThreshold: 1
      failureThreshold: 3
    readiness:
      path: /actuator/health
      initialDelaySeconds: 10
      periodSeconds: 10
      successThreshold: 1
      failureThreshold: 3
  env:
    javaOpts: "-Duser.timezone=Asia/Shanghai -XX:+UseContainerSupport -XX:MaxRAMPercentage=80"
  resources:
    requests:
      memory: "2Gi"
    limits:
      memory: "2Gi"
  service:
    type: ClusterIP
