server:
  address: 0.0.0.0
  port: 8080
spring:
  cloud:
    gateway:
      routes:
        - id: member
          uri: http://member-service:8081
          predicates:
            - Path=/members/**
          filters:
            - RewritePath=/members/(?<segment>.*), /members/$\{segment}
