apiVersion: v1
kind: Service
metadata:
  name: product-service
  namespace: default
  labels:
    app: product-service
spec:
  ports:
    - name: http
      port: 8082
      protocol: TCP
      targetPort: 8082
  selector:
    app: product-service
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-service
  namespace: default
  labels:
    app: product-service
    version: v1
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: product-service
      version: v1
  template:
    metadata:
      labels:
        app: product-service
        version: v1
    spec:
      serviceAccountName: shop
      containers:
        - image: registry.cn-shenzhen.aliyuncs.com/mrheaaaavy/shop-product-service:latest
          imagePullPolicy: Always
          name: product-service
          resources:
            requests:
              memory: "2Gi"
            limits:
              memory: "2Gi"
          command:
            - java
            - -Duser.timezone=Asia/Shanghai
            - -XX:ErrorFile=/dumps/hs_err_pid%p.log
            - -XX:+HeapDumpOnOutOfMemoryError
            - -XX:HeapDumpPath=/dumps/
            - -XX:+AlwaysPreTouch
            - -XX:+UseG1GC
            - -XX:+UseContainerSupport
            - -XX:MaxRAMPercentage=80
            - -XX:+ParallelRefProcEnabled
            - -Xlog:gc*
            - org.springframework.boot.loader.JarLauncher
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8082
            initialDelaySeconds: 5
            periodSeconds: 5
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8082
            initialDelaySeconds: 5
            periodSeconds: 5
          ports:
            - containerPort: 8082
              name: http
          volumeMounts:
            - mountPath: /dumps
              name: heap-dumps
      volumes:
        - name: heap-dumps
          emptyDir: {}
