apiVersion: v1
kind: Service
metadata:
  name: member-service
  labels:
    app.kubernetes.io/component: member-service
{{ include "shop-demo.labels" . | indent 4 }}
spec:
  type: {{ .Values.memberService.service.type }}
  ports:
    - port: {{ .Values.memberService.ports.external }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/component: member-service
    app.kubernetes.io/name: {{ include "shop-demo.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
