apiVersion: v1
kind: Service
metadata:
  name: trade-service
  namespace: default
  labels:
    app: trade-service
spec:
  ports:
    - name: http
      port: 8083
      protocol: TCP
      targetPort: 8083
  selector:
    app: trade-service
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: trade-service
  namespace: default
  labels:
    app: trade-service
    version: v1
spec:
  replicas: 1
  serviceName: trade-service
  selector:
    matchLabels:
      app: trade-service
      version: v1
  template:
    metadata:
      labels:
        app: trade-service
        version: v1
    spec:
      serviceAccountName: shop
      containers:
        - image: registry.cn-shenzhen.aliyuncs.com/mrheaaaavy/shop-trade-service:latest
          imagePullPolicy: IfNotPresent
          name: trade-service
          resources:
            requests:
              memory: "1Gi"
            limits:
              memory: "1Gi"
          command:
            - java
            - -Duser.timezone=Asia/Shanghai
            - -Xmx512M
            - -Xms512M
            - -XX:MaxMetaspaceSize=256M
            - -XX:MetaspaceSize=256M
            - -XX:+UseG1GC
            - -XX:MaxGCPauseMillis=100
            - -XX:+ParallelRefProcEnabled
            - -XX:+PrintGCDetails
            - org.springframework.boot.loader.JarLauncher
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8083
            initialDelaySeconds: 5
            periodSeconds: 5
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8083
            initialDelaySeconds: 5
            periodSeconds: 5
          ports:
            - containerPort: 8083
              name: http
